import type { Permiso, Rol } from "./index.js";

// ── Mapeo Rol → Permisos ──
export const ROL_PERMISOS: Record<Rol, Permiso[]> = {
  sistema: [
    "sistema:usuarios:listar",
    "sistema:usuarios:crear",
    "sistema:usuarios:editar",
    "sistema:usuarios:desactivar",
    "sistema:roles:asignar",
    "sistema:config:editar",
    "sistema:auditoria:ver",
    "sistema:plantillas:listar",
    "sistema:plantillas:crear",
    "sistema:plantillas:editar",
    "sistema:plantillas:eliminar",
    "negocio:servicios:listar",
    "negocio:reportes:ver",
    "negocio:dashboard:ver",
  ],
  administrador: [
    "negocio:servicios:crear",
    "negocio:servicios:editar",
    "negocio:servicios:asignar",
    "negocio:servicios:eliminar",
    "negocio:servicios:listar",
    "negocio:tareas:crear",
    "negocio:tareas:ejecutar",
    "negocio:tareas:supervisar",
    "negocio:areas:gestionar",
    "negocio:clientes:gestionar",
    "negocio:reportes:ver",
    "negocio:reportes:exportar",
    "negocio:dashboard:ver",
    "negocio:tiempo:registrar",
    "negocio:encuestas:ver",
  ],
  encargado: [
    "negocio:servicios:listar",
    "negocio:servicios:asignar",
    "negocio:tareas:crear",
    "negocio:tareas:ejecutar",
    "negocio:tareas:supervisar",
    "negocio:dashboard:ver",
    "negocio:reportes:ver",
    "negocio:tiempo:registrar",
  ],
  colaborador: [
    "negocio:servicios:listar",
    "negocio:tareas:ejecutar",
    "negocio:tiempo:registrar",
  ],
  cliente: [],
};
